"""empty message

Revision ID: 70ce0095c1cb
Revises: ceca59d14f0b
Create Date: 2025-05-29 14:35:47.953150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ce0095c1cb'
down_revision = 'ceca59d14f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
