"""empty message

Revision ID: 94f4166ed857
Revises: 70ce0095c1cb
Create Date: 2025-05-29 19:56:36.641401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f4166ed857'
down_revision = '70ce0095c1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
