"""empty message

Revision ID: ceca59d14f0b
Revises: fda831c389c5
Create Date: 2025-05-29 13:19:32.814403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceca59d14f0b'
down_revision = 'fda831c389c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
